project:
  type: website
  output-dir: docs

website:
  title: "olist_quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data.ipynb # Points directly to your notebook
        text: Data
      - href: model.ipynb # Points directly to your notebook
        text: Model
      - href: result.ipynb # Points directly to your notebook
        text: Results
    right:
      - href: about.qmd # Make sure you created this file (optional)
        text: About team

format:
  html:
    theme: flatly
    highlight: ayu
    toc: true
    code-fold: show # Allows users to see code
    df-print: paged

execute:
  echo: true # Ensures code is shown in the output
