project:
  type: website
  output-dir: ../docs
website:
  title: "olist_quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Data
      - href: model.qmd
        text: Model
      - href: result.qmd
        text: Results
    right:
      - href: about.qmd
        text: About team

format:
  html:
    theme: flatly
    highlight: ayu
    toc: true
    toc-location: right
    toc-depth: 1
    number-sections: false
    code-fold: true
    df-print: paged
